[global_shaders]
raygen = "simple.rgen"
miss = "black.rmiss"
emitter_hit = "emitter.rchit"

[camera]
view = '''
lookat 4 0 1   0 0 0    0 0 1
'''
fov = 70

[[light]]
type = "point"
color = [0.9, 0.9, 0.9]
position = [4, -2, 1]

[[brdf]]
name = "flat"
chit_shader = "flat.rchit"
[[brdf.field]]
name = "albedo"
type = "vec3"

[[object]]
mesh = "ajax.obj"
transform = '''
rotate 90 1 0 0
scale .4 .4 .4
translate 2 -5 0
rotate 170 0 0 1
scale .4 .4 .4
translate 2 0 -2
scale .6 .6 .6
translate .7 .5 0
'''
brdf = {name = "flat", fields = [[0.6, 0.6, 0.6]}
