[global_shaders]
raygen = "raygen.rgen"
miss = "black.rmiss"
emitter_hit = "emitter.rchit"

[camera]
view = '''
lookat 4 0 2   0 0 0    0 0 1
'''
fov = 70

[[light]]
type = "point"
color = [0.84, 0.76, 0.56]
position = [-5, -5, 10]

[[light]]
type = "point"
color = [0.5, 0.5, 0.5]
position = [5, 5, 10]

[[light]]
type = "area"
color = [0.5, 0.1, 0.5]
mesh = "square.obj"
transform = '''
rotate 45 0 0 1
translate 3 0 0
'''

[[brdf]]
name = "flat"
chit_shader = "flat.rchit"
[[brdf.field]]
name = "albedo"
type = "vec3"

[[object]]
mesh = "cube.obj"
transform = '''
identity
'''
brdf = {name = "flat", fields = [[0.2, 0.8, 0.2]]}

[[object]]
mesh = "cube.obj"
transform = '''
rotate 45 0 0 1
translate 1 1 0
'''
brdf = {name = "flat", fields = [[0.8, 0.2, 0.2]]}
