[global_shaders]
raygen = "path.rgen"
miss = "black.rmiss"
emitter_hit = "emitter.rchit"

[camera]
view = '''
lookat 0 30 12   0 0 0    0 0 1
'''
fov = 30

[[light]]
type = "area"
color = [40, 40, 40]
mesh = "square.obj"
transform = '''
rotate 180 1 0 0
translate -0.5 -0.5 0
scale 10 10 1
translate 0 5 50
'''

[[brdf]]
name = "diffuse"
chit_shader = "diffuse.rchit"
[[brdf.field]]
name = "albedo"
type = "vec3"

[[brdf]]
name = "microfacet"
chit_shader = "microfacet.rchit"
[[brdf.field]]
name = "albedo"
type = "vec3"
[[brdf.field]]
name = "ior"
type = "float"
[[brdf.field]]
name = "roughness"
type = "float"

[[object]]
mesh = "cylinder.obj"
transform = '''
rotate 90 1 0 0
scale 4 4 0.015
'''
brdf = {name = "diffuse", fields = [[0.1, 0.1, 0.1]]}

[[object]]
mesh = "cube.obj"
transform = '''
scale 3.1 3.1 3.1
rotate 47.5 0 0 1
translate 1 -6.5 0
'''
brdf = {name = "diffuse", fields = [[0.8, 0.8, 0.8]]}

[[object]]
mesh = "cube.obj"
transform = '''
scale 3.6 3.6 3.6
rotate 72 0 0 1
translate -2.2 -1.8 0
'''
brdf = {name = "diffuse", fields = [[0.001, 0.015, 0.011]]}

[[object]]
mesh = "cube.obj"
transform = '''
rotate 64 0 0 1
scale 1.3 1.3 1.3
translate -2.2 0.2 3.6
'''
brdf = {name = "diffuse", fields = [[0.01, 0.01, 0.01]]}

[[object]]
mesh = "cube.obj"
transform = '''
rotate 45 1 -1 0
scale 0.8 0.8 0.8
translate 0 2 0
'''
brdf = {name = "diffuse", fields = [[0.05, 0.05, 0.05]]}

[[object]]
mesh = "cube.obj"
transform = '''
rotate 30 0 0 1
scale 2.4 2.4 2.4
translate 2.5 -1.5 0
'''
brdf = {name = "microfacet", fields = [[0.226, 0.121, 0.054], 1.57, 0.05]}

[[object]]
mesh = "cube.obj"
transform = '''
rotate 90 0 0 1
scale 1.3 1.3 1.3
translate 6.8 -1.5 0
'''
brdf = {name = "diffuse", fields = [[0.01, 0.01, 0.01]]}

[[object]]
mesh = "cube.obj"
transform = '''
rotate 90 0 0 1
scale 0.8 0.8 0.8
translate 5 6 0
'''
brdf = {name = "diffuse", fields = [[0.01, 0.01, 0.01]]}
